name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # install project
          pip install -r requirements-dev.txt

      - name: Run black
        run: black . --check
      - name: Run isort
        run: isort . --check-only
      - name: Run ruff
        run: ruff check .

      - name: Run tests
        run: pytest -q
